package bitcoin

const (
	// TestMnemonicPhrase is a sample mnemonic phrase generated by GenerateMnemonic() function
	TestMnemonicPhrase = "apology guide protect raven month jump very gloom coconut bean inherit subway blood run novel jacket never shop bread denial thought maid exist"
)
